[package]
name = "image-manipulation"
version = "0.1.0"
authors = ["Alexander Mattheis <alexander.mattheis@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
image = "0.23.1"
plotly = "0.4.1"
