pub mod auto_contrast;
pub mod brightness;
pub mod contrast;
pub mod gamma;
pub mod histogram_equalization;
pub mod histogram_specification;
pub mod inversion;
pub mod linear_blending;
pub mod threshold;